import React, { useState, useMemo } from 'react';
import { Eveniment, Rezultat, Sportiv, Plata, PretConfig, Participare, Examen, Grad } from '../types';
import { Button, Modal, Input, Select, Card, ConfirmationModal } from './ui';
import { PlusIcon, EditIcon, TrashIcon, ArrowLeftIcon } from './icons';
import { getPretValabil } from '../utils/pricing';
import { supabase } from '../supabaseClient';

const formatDateRange = (start: string) => new Date(start).toLocaleDateString('ro-RO');
const EvenimentForm: React.FC<{ isOpen: boolean; onClose: () => void; onSave: (ev: Omit<Eveniment, 'id'>) => Promise<void>; evToEdit: Eveniment | null; type: 'Stagiu' | 'Competitie'; }> = ({ isOpen, onClose, onSave, evToEdit, type }) => {
    const [formState, setFormState] = useState<Omit<Eveniment, 'id' | 'probe_disponibile'>>({ denumire: '', data: new Date().toISOString().split('T')[0], locatie: '', organizator: '', tip: type });
    const [probeStr, setProbeStr] = useState('');
    const [loading, setLoading] = useState(false);
    React.useEffect(() => { if (isOpen) { if (evToEdit) { setFormState({ denumire: evToEdit.denumire, data: evToEdit.data, locatie: evToEdit.locatie, organizator: evToEdit.organizator, tip: evToEdit.tip }); setProbeStr(evToEdit.probe_disponibile?.join(', ') || ''); } else { setFormState({ denumire: '', data: new Date().toISOString().split('T')[0], locatie: '', organizator: '', tip: type }); setProbeStr(''); } } }, [evToEdit, isOpen, type]);
    const handleChange = (e: React.ChangeEvent<HTMLInputElement|HTMLSelectElement>) => setFormState(p => ({ ...p, [e.target.name]: e.target.value }));
    const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); const eventData: Omit<Eveniment, 'id'> = { ...formState, ...(type === 'Competitie' && { probe_disponibile: probeStr.split(',').map(p => p.trim()).filter(Boolean) }) }; await onSave(eventData); setLoading(false); onClose(); };
    return ( <Modal isOpen={isOpen} onClose={onClose} title={evToEdit ? `Editează ${type}` : `Adaugă ${type} Nou`}> <form onSubmit={handleSubmit} className="space-y-4"> <Input label="Denumire" name="denumire" value={formState.denumire} onChange={handleChange} required /> <Input label="Data Eveniment" name="data" type="date" value={formState.data} onChange={handleChange} required /> <Input label="Locație" name="locatie" value={formState.locatie} onChange={handleChange} /> <Input label="Organizator" name="organizator" value={formState.organizator} onChange={handleChange} /> {type === 'Competitie' && ( <Input label="Probe (separate prin virgulă)" name="probe" value={probeStr} onChange={(e) => setProbeStr(e.target.value)} placeholder="Ex: Quyen, Song Dau" /> )} <div className="flex justify-end pt-4 space-x-2"><Button type="button" variant="secondary" onClick={onClose} disabled={loading}>Anulează</Button><Button variant="success" type="submit" disabled={loading}>{loading ? 'Se salvează...' : 'Salvează'}</Button></div> </form> </Modal> );
};
const EvenimentDetail: React.FC<{ eveniment: Eveniment; rezultate: Rezultat[]; setRezultate: React.Dispatch<React.SetStateAction<Rezultat[]>>; sportivi: Sportiv[]; setPlati: React.Dispatch<React.SetStateAction<Plata[]>>; preturiConfig: PretConfig[]; participari: Participare[]; examene: Examen[]; grade: Grad[]; }> = ({ eveniment, rezultate, setRezultate, sportivi, setPlati, preturiConfig, participari, examene, grade }) => {
    const [sportivId, setSportivId] = useState('');
    const [showSuccess, setShowSuccess] = useState<string | null>(null);
    const [rezultatToDelete, setRezultatToDelete] = useState<Rezultat | null>(null);
    const [deleteLoading, setDeleteLoading] = useState(false);
    const sortedRezultate = useMemo(() => { const getGradOrder = (s: Sportiv) => { const admitted = participari.filter(p => p.sportiv_id === s.id && p.rezultat === 'Admis').map(p => ({ ...p, examen: examene.find(e => e.id === p.examen_id) })).filter(p => p.examen).sort((a, b) => new Date(b.examen!.data).getTime() - new Date(a.examen!.data).getTime()); if (admitted.length === 0) return 0; const currentGrad = grade.find(g => g.id === admitted[0].grad_sustinut_id); return currentGrad ? currentGrad.ordine : 0; }; return [...rezultate].sort((a, b) => { const sA = sportivi.find(s => s.id === a.sportiv_id); const sB = sportivi.find(s => s.id === b.sportiv_id); if (!sA || !sB) return 0; const gradOrderA = getGradOrder(sA); const gradOrderB = getGradOrder(sB); if (gradOrderB !== gradOrderA) return gradOrderB - gradOrderA; return `${sA.nume} ${sA.prenume}`.localeCompare(`${sB.nume} ${sB.prenume}`); }); }, [rezultate, sportivi, participari, examene, grade]);
    const handleAddParticipant = async (e: React.FormEvent) => { e.preventDefault(); if (!supabase) return; const sportiv = sportivi.find(s => s.id === sportivId); if (!sportiv || rezultate.some(r => r.sportiv_id === sportivId)) return; const { data: rData, error: rError } = await supabase.from('rezultate').insert({ eveniment_id: eveniment.id, sportiv_id: sportivId, rezultat: 'Înscris' }).select().single(); if (rError) return; const cat: PretConfig['categorie'] = eveniment.tip === 'Stagiu' ? 'Taxa Stagiu' : 'Taxa Competitie'; const pret = getPretValabil(preturiConfig, cat, eveniment.data); if (pret) { const newPlata = { sportiv_id: sportiv.id, familie_id: sportiv.familie_id, suma: pret.suma, data: new Date().toISOString().split('T')[0], status: 'Neachitat' as const, descriere: `Taxa ${eveniment.denumire}`, tip: cat, observatii: `` }; const { data: pData, error: pError } = await supabase.from('plati').insert(newPlata).select().single(); if (pData) setPlati(prev => [...prev, pData as Plata]); } if(rData) setRezultate(prev => [...prev, rData as Rezultat]); setShowSuccess(`Participant adăugat.`); setTimeout(() => setShowSuccess(null), 4000); setSportivId(''); };
    const handleUpdateRezultat = async (id: string, updates: Partial<Rezultat>) => { if (!supabase) return; const {data, error} = await supabase.from('rezultate').update(updates).eq('id', id).select().single(); if (data) { setRezultate(prev => prev.map(r => r.id === id ? data as Rezultat : r)); }};
    const confirmDeleteRezultat = async () => { if(!supabase || !rezultatToDelete) return; setDeleteLoading(true); const {error} = await supabase.from('rezultate').delete().eq('id', rezultatToDelete.id); setDeleteLoading(false); if(!error) { setRezultate(prev => prev.filter(r => r.id !== rezultatToDelete.id)); } setRezultatToDelete(null); };
    const handleProbeChange = (id: string, proba: string, isChecked: boolean) => { const r = rezultate.find(r => r.id === id); if(!r) return; const probes = r.probe ? r.probe.split(',').map(p => p.trim()).filter(Boolean) : []; const newProbes = isChecked ? [...new Set([...probes, proba])] : probes.filter(p => p !== proba); handleUpdateRezultat(id, { probe: newProbes.join(', ') }); };
    return ( <Card> <h3 className="text-2xl font-bold text-white">{eveniment.denumire} - {formatDateRange(eveniment.data)}</h3> <p className="text-slate-400">{eveniment.locatie} (Org: {eveniment.organizator})</p> <div className="mt-6 pt-6 border-t border-slate-700"> <h4 className="text-xl font-semibold mb-4 text-white">Participanți & Rezultate</h4> <div className="space-y-2 mb-6"> {sortedRezultate.map(r => { const sportiv = sportivi.find(s => s.id === r.sportiv_id); return ( <div key={r.id} className="bg-slate-700 p-3 rounded-md grid grid-cols-1 md:grid-cols-4 gap-4 items-center"> <p className="font-medium">{sportiv?.nume} {sportiv?.prenume}</p> <Input label="" value={r.rezultat} onBlur={e => handleUpdateRezultat(r.id, { rezultat: e.target.value })} onChange={e => setRezultate(prev => prev.map(res => res.id === r.id ? {...res, rezultat: e.target.value} : res))} /> {eveniment.tip === 'Competitie' && ( <div className="flex flex-wrap items-center gap-x-4 gap-y-2"> {eveniment.probe_disponibile?.map(proba => ( <label key={proba} className="flex items-center space-x-2 text-sm"><input type="checkbox" checked={r.probe?.includes(proba) || false} onChange={(e) => handleProbeChange(r.id, proba, e.target.checked)} /><span>{proba}</span></label> ))} </div> )} <Button onClick={() => setRezultatToDelete(r)} variant="danger" size="sm" className="justify-self-end md:col-start-4"><TrashIcon /></Button> </div> ) })} {rezultate.length === 0 && <p className="text-slate-400">Niciun participant.</p>} </div> <Card className="bg-slate-900/50"> <h5 className="text-lg font-semibold mb-2">Adaugă Participant</h5> <form onSubmit={handleAddParticipant} className="grid grid-cols-1 md:grid-cols-3 gap-4 items-end"> <div className="col-span-2"> <Select label="Sportiv" value={sportivId} onChange={e => setSportivId(e.target.value)}> <option value="">Selectează</option> {sportivi.filter(s => s.status === 'Activ' && !rezultate.some(p => p.sportiv_id === s.id)).map(s => ( <option key={s.id} value={s.id}>{s.nume} {s.prenume}</option> ))} </Select> </div> <Button type="submit" variant="info">Adaugă</Button> </form> {showSuccess && <p className="text-green-400 mt-2 text-sm">{showSuccess}</p>} </Card> </div> <ConfirmationModal isOpen={!!rezultatToDelete} onClose={() => setRezultatToDelete(null)} onConfirm={confirmDeleteRezultat} title="Confirmare" message="Sunteți sigur?" loading={deleteLoading}/> </Card> );
};
export const StagiiCompetitiiManagement: React.FC<{ onBack: () => void; type: 'Stagiu' | 'Competitie'; evenimente: Eveniment[]; setEvenimente: React.Dispatch<React.SetStateAction<Eveniment[]>>; rezultate: Rezultat[]; setRezultate: React.Dispatch<React.SetStateAction<Rezultat[]>>; sportivi: Sportiv[]; setPlati: React.Dispatch<React.SetStateAction<Plata[]>>; preturiConfig: PretConfig[]; participari: Participare[]; examene: Examen[]; grade: Grad[]; }> = ({ onBack, type, evenimente, setEvenimente, rezultate, setRezultate, sportivi, setPlati, preturiConfig, participari, examene, grade }) => {
    const [isFormOpen, setIsFormOpen] = useState(false);
    const [evToEdit, setEvToEdit] = useState<Eveniment | null>(null);
    const [selectedEv, setSelectedEv] = useState<Eveniment | null>(null);
    const [eventToDelete, setEventToDelete] = useState<Eveniment | null>(null);
    const [deleteLoading, setDeleteLoading] = useState(false);
    const handleSave = async (evData: Omit<Eveniment, 'id'>) => { if (!supabase) return; if (evToEdit) { const { data, error } = await supabase.from('evenimente').update(evData).eq('id', evToEdit.id).select().single(); if(data) setEvenimente(prev => prev.map(e => e.id === evToEdit.id ? data as Eveniment : e)); } else { const { data, error } = await supabase.from('evenimente').insert(evData).select().single(); if (data) setEvenimente(prev => [...prev, data as Eveniment]); } };
    const confirmDelete = async () => { if (!supabase || !eventToDelete) return; setDeleteLoading(true); const evId = eventToDelete.id; await supabase.from('rezultate').delete().eq('eveniment_id', evId); await supabase.from('evenimente').delete().eq('id', evId); setDeleteLoading(false); setEvenimente(prev => prev.filter(e => e.id !== evId)); setRezultate(prev => prev.filter(p => p.eveniment_id !== evId)); if (selectedEv?.id === evId) setSelectedEv(null); setEventToDelete(null); };
    const filteredEvenimente = evenimente.filter(ev => ev.tip === type);
    const sortedEvenimente = [...filteredEvenimente].sort((a,b) => new Date(b.data).getTime() - new Date(a.data).getTime());
    if(selectedEv) { return ( <div> <Button onClick={() => setSelectedEv(null)} className="mb-4" variant="secondary"><ArrowLeftIcon className="w-5 h-5 mr-2" /> Listă</Button> <EvenimentDetail eveniment={selectedEv} rezultate={rezultate.filter(r => r.eveniment_id === selectedEv.id)} setRezultate={setRezultate} sportivi={sportivi} setPlati={setPlati} preturiConfig={preturiConfig} participari={participari} examene={examene} grade={grade} /> </div> ); }
    return ( <div> {onBack && <Button onClick={onBack} variant="secondary" className="mb-6"><ArrowLeftIcon className="w-5 h-5 mr-2" /> Meniu</Button>} <div className="flex justify-between items-center mb-6"> <h1 className="text-3xl font-bold text-white">{type === 'Stagiu' ? 'Stagii' : 'Competiții'}</h1> <Button onClick={() => { setEvToEdit(null); setIsFormOpen(true); }} variant="info"><PlusIcon className="w-5 h-5 mr-2" />Adaugă {type}</Button> </div> <div className="hidden md:block bg-slate-800/50 rounded-lg border border-slate-700 overflow-hidden"> <table className="w-full text-left"> <thead className="bg-slate-700/50"><tr>{['Eveniment', 'Data', 'Participanți', 'Acțiuni'].map(h => <th key={h} className="p-4 font-semibold">{h}</th>)}</tr></thead> <tbody className="divide-y divide-slate-700"> {sortedEvenimente.map(ev => ( <tr key={ev.id} className="hover:bg-slate-700/30"> <td className="p-4 font-medium cursor-pointer" onClick={() => setSelectedEv(ev)}>{ev.denumire}</td> <td className="p-4 cursor-pointer" onClick={() => setSelectedEv(ev)}>{formatDateRange(ev.data)}</td> <td className="p-4">{rezultate.filter(p => p.eveniment_id === ev.id).length}</td> <td className="p-4 text-right w-32"><div className="flex justify-end gap-2"><Button onClick={() => {setEvToEdit(ev); setIsFormOpen(true);}} variant="primary" size="sm"><EditIcon /></Button><Button onClick={() => setEventToDelete(ev)} variant="danger" size="sm"><TrashIcon /></Button></div></td> </tr> ))} </tbody> </table> {sortedEvenimente.length === 0 && <p className="p-4 text-center">Niciun eveniment.</p>} </div> <div className="md:hidden grid grid-cols-1 gap-4"> {sortedEvenimente.map(ev => ( <Card key={ev.id} className="p-0 overflow-hidden" onClick={() => setSelectedEv(ev)}> <div className="p-4"> <h3 className="font-bold text-lg">{ev.denumire}</h3> <p className="text-sm text-slate-400">{formatDateRange(ev.data)}</p> <p className="text-sm mt-2">Participanți: <span className="font-bold">{rezultate.filter(p => p.eveniment_id === ev.id).length}</span></p> </div> <div className="bg-slate-900/50 p-2 flex justify-end gap-2"> <Button onClick={(e) => { e.stopPropagation(); setEvToEdit(ev); setIsFormOpen(true);}} variant="primary" size="sm"><EditIcon /></Button> <Button onClick={(e) => { e.stopPropagation(); setEventToDelete(ev);}} variant="danger" size="sm"><TrashIcon /></Button> </div> </Card> ))} </div> <EvenimentForm isOpen={isFormOpen} onClose={() => setIsFormOpen(false)} onSave={handleSave} evToEdit={evToEdit} type={type} /> <ConfirmationModal isOpen={!!eventToDelete} onClose={() => setEventToDelete(null)} onConfirm={confirmDelete} title={`Ștergere ${type}`} message="Sunteți sigur?" loading={deleteLoading}/> </div> );
};
