import type { ThemeConfig } from '../types';

export const DEFAULT_THEME: ThemeConfig = {
  name: 'QwanKiDo Blue',
  bg: '#020617',
  surface: '#0f172a',
  surface2: '#1e293b',
  border: '#1e293b',
  text: '#f8fafc',
  textMuted: '#94a3b8',
  primary: '#3b82f6',
  primaryHover: '#2563eb',
  primaryFg: '#ffffff',
  secondary: '#1e293b',
  secondaryHover: '#334155',
  secondaryFg: '#e2e8f0',
  sidebarBg: '#020617',
  sidebarText: '#94a3b8',
  sidebarActive: '#3b82f6',
  sidebarActiveFg: '#ffffff',
};

export const PREDEFINED_THEMES: ThemeConfig[] = [
  DEFAULT_THEME,
  {
    name: 'Midnight Navy',
    bg: '#020617',
    surface: '#0c1526',
    surface2: '#122240',
    border: '#1a2f52',
    text: '#f8fafc',
    textMuted: '#94a3b8',
    primary: '#1d4ed8',
    primaryHover: '#1e40af',
    primaryFg: '#ffffff',
    secondary: '#0c1526',
    secondaryHover: '#122240',
    secondaryFg: '#bfdbfe',
    sidebarBg: '#010b18',
    sidebarText: '#7ea5c8',
    sidebarActive: '#1d4ed8',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Forest',
    bg: '#021208',
    surface: '#052e16',
    surface2: '#0a4023',
    border: '#14532d',
    text: '#f8fafc',
    textMuted: '#86efac',
    primary: '#16a34a',
    primaryHover: '#15803d',
    primaryFg: '#ffffff',
    secondary: '#052e16',
    secondaryHover: '#0a4023',
    secondaryFg: '#dcfce7',
    sidebarBg: '#021208',
    sidebarText: '#6ee7a0',
    sidebarActive: '#16a34a',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Crimson',
    bg: '#0f0505',
    surface: '#1c0a0a',
    surface2: '#2d1010',
    border: '#450a0a',
    text: '#f8fafc',
    textMuted: '#fca5a5',
    primary: '#dc2626',
    primaryHover: '#b91c1c',
    primaryFg: '#ffffff',
    secondary: '#1c0a0a',
    secondaryHover: '#2d1010',
    secondaryFg: '#fee2e2',
    sidebarBg: '#0f0505',
    sidebarText: '#f87171',
    sidebarActive: '#dc2626',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Violet',
    bg: '#0a0514',
    surface: '#13082b',
    surface2: '#1f0e42',
    border: '#2e1065',
    text: '#f8fafc',
    textMuted: '#c4b5fd',
    primary: '#7c3aed',
    primaryHover: '#6d28d9',
    primaryFg: '#ffffff',
    secondary: '#13082b',
    secondaryHover: '#1f0e42',
    secondaryFg: '#ede9fe',
    sidebarBg: '#0a0514',
    sidebarText: '#a78bfa',
    sidebarActive: '#7c3aed',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Amber',
    bg: '#0c0a02',
    surface: '#1c1a05',
    surface2: '#292508',
    border: '#3d3400',
    text: '#f8fafc',
    textMuted: '#fcd34d',
    primary: '#d97706',
    primaryHover: '#b45309',
    primaryFg: '#ffffff',
    secondary: '#1c1a05',
    secondaryHover: '#292508',
    secondaryFg: '#fef3c7',
    sidebarBg: '#0c0a02',
    sidebarText: '#fbbf24',
    sidebarActive: '#d97706',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Ocean',
    bg: '#020c0f',
    surface: '#0c1e24',
    surface2: '#102d36',
    border: '#164e63',
    text: '#f8fafc',
    textMuted: '#67e8f9',
    primary: '#0891b2',
    primaryHover: '#0e7490',
    primaryFg: '#ffffff',
    secondary: '#0c1e24',
    secondaryHover: '#102d36',
    secondaryFg: '#cffafe',
    sidebarBg: '#020c0f',
    sidebarText: '#67e8f9',
    sidebarActive: '#0891b2',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Graphite',
    bg: '#030303',
    surface: '#111111',
    surface2: '#1a1a1a',
    border: '#262626',
    text: '#f5f5f5',
    textMuted: '#a3a3a3',
    primary: '#525252',
    primaryHover: '#404040',
    primaryFg: '#ffffff',
    secondary: '#111111',
    secondaryHover: '#1a1a1a',
    secondaryFg: '#e5e5e5',
    sidebarBg: '#030303',
    sidebarText: '#737373',
    sidebarActive: '#525252',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Office Light',
    bg: '#f4f6fa',
    surface: '#ffffff',
    surface2: '#f1f5f9',
    border: '#e2e8f0',
    text: '#1e293b',
    textMuted: '#64748b',
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    primaryFg: '#ffffff',
    secondary: '#f1f5f9',
    secondaryHover: '#e2e8f0',
    secondaryFg: '#334155',
    sidebarBg: '#1e3a5f',
    sidebarText: '#cbd5e1',
    sidebarActive: '#3b82f6',
    sidebarActiveFg: '#ffffff',
  },
  {
    name: 'Snow',
    bg: '#ffffff',
    surface: '#f8fafc',
    surface2: '#f1f5f9',
    border: '#e2e8f0',
    text: '#0f172a',
    textMuted: '#475569',
    primary: '#7c3aed',
    primaryHover: '#6d28d9',
    primaryFg: '#ffffff',
    secondary: '#f1f5f9',
    secondaryHover: '#e2e8f0',
    secondaryFg: '#334155',
    sidebarBg: '#4c1d95',
    sidebarText: '#ddd6fe',
    sidebarActive: '#7c3aed',
    sidebarActiveFg: '#ffffff',
  },
];

export function applyTheme(theme: ThemeConfig): void {
  const root = document.documentElement;
  root.style.setProperty('--t-bg', theme.bg);
  root.style.setProperty('--t-surface', theme.surface);
  root.style.setProperty('--t-surface-2', theme.surface2);
  root.style.setProperty('--t-border', theme.border);
  root.style.setProperty('--t-text', theme.text);
  root.style.setProperty('--t-text-muted', theme.textMuted);
  root.style.setProperty('--t-primary', theme.primary);
  root.style.setProperty('--t-primary-hover', theme.primaryHover);
  root.style.setProperty('--t-primary-fg', theme.primaryFg);
  root.style.setProperty('--t-secondary', theme.secondary);
  root.style.setProperty('--t-secondary-hover', theme.secondaryHover);
  root.style.setProperty('--t-secondary-fg', theme.secondaryFg);
  root.style.setProperty('--t-sidebar-bg', theme.sidebarBg);
  root.style.setProperty('--t-sidebar-text', theme.sidebarText);
  root.style.setProperty('--t-sidebar-active', theme.sidebarActive);
  root.style.setProperty('--t-sidebar-active-fg', theme.sidebarActiveFg);
}
